name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  ANDROID_NDK_VERSION: r25c
  ANDROID_ABI: arm64-v8a

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Clone playlang repository
      uses: actions/checkout@v4
      with:
        repository: vrolife/playlang
        # 如果是私有仓库需要添加token
        token: ${{ secrets.GITHUB_TOKEN }}
        path: playlang

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Setup Android NDK
      uses: android-actions/setup-android@v2
      with:
        ndk-version: ${{ env.ANDROID_NDK_VERSION }}

    - name: Install Python package
      working-directory: ./playlang
      run: python3 setup.py install

    - name: Configure CMake
      working-directory: ./playlang
      run: |
        cmake --preset dev-host-libc++ -B build \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ env.ANDROID_ABI }} \
          -DANDROID_NATIVE_API_LEVEL=21

    - name: Build project
      working-directory: ./playlang
      run: cmake --build build --parallel $(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-build
        path: playlang/build/src/mypower
