name: Android CI

on:
  workflow_dispatch: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  ANDROID_NDK_VERSION: r25c
  ANDROID_ABI: arm64-v8a
    
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
       
    - name: Clone playlang repository
      run: git clone https://github.com/ShirokoLEET/playlang.git

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Setup Android NDK
      uses: android-actions/setup-android@v2

    - name: Install Python package
      working-directory: ./playlang
      run: python3 setup.py install
      
    - name: LS
      run: ls

    - name: Configure CMake
      run: |
        cmake --preset dev-arm64 -B build \
          -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake \
          -DANDROID_ABI=${{ env.ANDROID_ABI }} \
          -DANDROID_NATIVE_API_LEVEL=21

    - name: Build project
      working-directory: ./playlang
      run: cmake --build build --parallel $(nproc)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-build
        path: playlang/build/src/mypower
